# Generated by Django 4.1.7 on 2023-03-04 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_issueditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issueditems',
            new_name='Issued_Items',
        ),
        migrations.AlterModelOptions(
            name='issued_items',
            options={'verbose_name_plural': 'Issued_Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
