# Generated by Django 4.1.7 on 2023-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_issueditems_issued_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
